spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    username: root
    password: Aswd1234
    url: jdbc:mysql://localhost:3306/spring_data_test
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
#==================== logging Setting =====================#
logging:
  level:
    org.springframework: info
    org.hibernate: info
    com.test: debug
  file: logs/spring-data.log

server:
  port: 10088
####################################################################Code##############################################################
